version: '3.8'

services:
  backend:
    image: danhkay2005/mern-backend:1.0
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://lehoangdanh:Danh10112005@235087-lehoangdanh.sptpohy.mongodb.net/cloud_lab?retryWrites=true&w=majority
    networks:
      - mern-net

  frontend:
    image: danhkay2005/mern-frontend:2.0
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge